version: '3.8'
services:
  db:
    container_name: MongoDB
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_PASS}'

    ports:
      - '27017:27017'
    expose:
      - '27017'